### ISSUE TITLE
Transpiled code is ES6 instead of ES5

### ISSUE THREAD

**Issue by Ronsku** [Dynalon/reactive-state#10]
Hi,

I upgraded reactive-state from 0.4.5 -> 0.5.3 (No idea what the version updates with 0.8.x in between are, but they are obviously not pushed to the NPM repository).

I've got issues now with the upgrade since code in `src` (old `dist`) is in ES6. Before it was in ES5 as it should. tsconfig.json says target ES5 and that is perfect, but build is wrong currently in latest version.

Screenshot from 0.5.3 (ES6):
![screen shot 2018-01-11 at 13 06 48](https://user-images.githubusercontent.com/7983358/34822663-5b1c0cbc-f6d0-11e7-8220-4f709b8eb0c5.png)

Screenshot from 0.4.5 (ES5):
![screen shot 2018-01-11 at 13 08 08](https://user-images.githubusercontent.com/7983358/34822703-809ff61a-f6d0-11e7-945d-6167163d5926.png)

I would love to have it in ES5 format like before. Is this a mistake or a change made on purpose?

Thank you Timo!

**Comment by Dynalon** [comment]
This might be related to the test code, as I compile the code for running in tests to ES6 (for coverage reasons). But at the same time, compiled code should not go to /dist/ any longer (maybe for the tests, but not for consumption/release).

All .js files should go into /src/. Did you `import {}` directly from `reactive-state/dist/*` ? If so, try only to import like this: `import { Store, Action, Reducer } from 'reactive-state'` or, when using the react-bridge: `import { connect }  from 'reactive-state/react'

**Comment by Dynalon** [comment]
Another note: If you cloned reactive-state locally, try a `git clean -xfd` and re-run `npm install && npm run build` manually

**Comment by Ronsku** [comment]
In 0.5.3 there aren't anymore all the `dist` files.
![screen shot 2018-01-11 at 13 29 51](https://user-images.githubusercontent.com/7983358/34823561-8a83675e-f6d3-11e7-9e4f-dac757963bd8.png)


also in `package.json`: `"main": "src/index.js",` so when you just import `import { Store, Action, Reducer } from 'reactive-state'` it will always go to the `src/`.

**Comment by Ronsku** [comment]
Yes, everything goes into `src/`-folder and also the `package.json`-linking. All files in `src/` are ES6. Could `src/`-folder files be in ES5 in NPM repository?

**Comment by Ronsku** [comment]
Yes, everything goes into src/-folder and also the package.json-linking. All files in src/ are ES6. Could src/-folder files be in ES5 in NPM repository?

**Comment by Dynalon** [comment]
Uuuh my bad, the "npm run build-test" actually replaces the src/ files with ES6 versions, and I accidentally published those. Just publish v0.5.4 that fixes this. Will need to find another solution for the test compiltion.

**Comment by Dynalon** [comment]
I registered a prepublish hook that should prevent this happening in the future.

**Comment by Ronsku** [comment]
Amazing! Thank you once again! 👍  :)
