### ISSUE TITLE
Upgrade to RxJS 6.1.0

### ISSUE THREAD

**Issue by Ronsku** [Dynalon/reactive-state#14]
Hi again,

Would it be possible to upgrade reactive-state to RxJS 6, since it's been out for a while now and seems stable.

The project migration from 5.5.10 -> 6.1.0 has been made easy with automated tools.
[https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

Since reactive-state is such a compact and well made project I think it would be easy to migrate it without `rxjs-compat`. This package shouldn't be installed on third party libraries anyway, since it of course forces it on the applications using the library as well.

Thanks 👍 🙂

**Comment by Dynalon** [comment]
Hi Ron,

I've already done that upgrade in the `next` branch (npm packages also available via `npm install reactive-state@next`. Although I did some breaking API changes, so if you upgrade make sure to check the changelog: https://github.com/Dynalon/reactive-state/blob/next/CHANGELOG.md

Let me know if you have any problems or bugs with the new API; am planning to release 2.0 next week.

**Comment by Dynalon** [comment]
Closing this as I released 2.0 (92367ddea577f43ec829963a0aa7f6c5ffe38737) which by default uses RxJS 6.1.0.

**Comment by Ronsku** [comment]
Thank you so much, this is an superb update! 🎉
