### ISSUE TITLE
Upgrade to rxjs@6.3.3

### ISSUE THREAD

**Issue by cramatt** [Dynalon/reactive-state#16]
https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#633-2018-09-25

**Comment by Dynalon** [comment]
I've upgraded to 6.3.3 in `master`, though `6.4.0` is current. I have not yet published a new release.

You should be able to upgrade to 6.3.3 in your project using the latest release. As I know sometimes when using TypeScript there might be issues with different rxjs version, let me know if this raises some kind of errors for you.
