### ISSUE TITLE
Remove istanbul from optionalDependencies

### ISSUE THREAD

**Issue by villelahdenvuo** [Dynalon/reactive-state#46]
It's not needed for functionality.

```
# npm audit report
async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install reactive-state@3.2.1, which is a breaking change
node_modules/istanbul/node_modules/async
  istanbul  *
  Depends on vulnerable versions of async
  node_modules/istanbul
    reactive-state  >=3.3.0-beta.0
    Depends on vulnerable versions of istanbul
    node_modules/reactive-state
```

**Comment by Dynalon** [comment]
What do you mean it is not needed, it is used to asses test coverage. If istanbul is to be removed, there must be a replacement lib. note that this is a build-dep (devDependency) only, so as a user of reactive-state you are not affected at all by the vulnerability.

**Comment by villelahdenvuo** [comment]
@Dynalon Sorry for the confusion. Currently instanbul is listed in the optionalDependencies: https://github.com/Dynalon/reactive-state/blob/master/package.json#L80

Therefore NPM tries to install it (and succeeds!). It should be moved to devDependencies like you said.

**Comment by villelahdenvuo** [comment]
Also, istanbul says it's deprecated and should be replaced with nyc.

**Comment by Dynalon** [comment]
I'll happily accept a PR that upgrades to nyc.
