### ISSUE TITLE
reactive-state with lettable-operators

### ISSUE THREAD

**Issue by Ronsku** [Dynalon/reactive-state#7]
Hi,

An amazing update to rxjs with lettable-operators instead of this endless patching on Observables and rxjs import hell.

https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md
in
https://github.com/ReactiveX/rxjs/releases/tag/5.5.0-beta.0

Could we upgrade reactive-state to use this? I would happily contribute to this as well. Let me know what you think! :)

**Comment by Dynalon** [comment]
I keep a close eye on letable operators. They have not landed in a stable rxjs release, but as soon as they are out I will consider upgrading.

As far as I can see it currently, there is no advantage of using them in `reactive-state`. We do not provide own custom operators, and we are only using a very small amount of operators from rxjs that are explicitly added using `import "rxjs/add/operator/*"` syntax (In contrast to including all operators). So only the operators we use land in the outputed bundle (if you are using webpack/rollup). The only real benefit would be that we could save some bytes when the external project that uses `reactive-state` uses letable operators and uses operators we do; in this case the operators would not be bundled twice.

As soon as a stable rxjs version with letable operators is out I will test if the save in bytes justifies the switch to a little more cumbersome syntax.

**Comment by Dynalon** [comment]
For the one benefit, the other way arounds holds true: If you use `reactive-state` in your project and DO NOT use letable operators but `reactive-state` would, the operators would still end up being bundled twice. So the one advantage becomes a disadvantage in other cases. 

However letable operators might be the future, so switching is an option.

**Comment by Dynalon** [comment]
See some new comments on closed PR #8

**Comment by Ronsku** [comment]
Good points. I'm just starting a new project where bundle size matters a lot. I was very happy to see that RxJS finally have made it possible use Lodash -like functional programming.

**Comment by Dynalon** [comment]
fixed by 921d922331ca99565cc
